services:
  grafana:
    extends:
      file: ${MODE}.yaml
      service: grafana
    build:
      context: ..
      args:
        GRAFANA_VERSION: "$VERSION_GRAFANA"
      tags:
        - "${COMPOSE_PROJECT_NAME}/grafana:${VERSION_GRAFANA}"
    secrets:
      - source: grafana_postgresql_password
        target: postgresql_password
      - source: grafana_metrics_password
        target: metrics_password
      - source: grafana_oidc_secret
        target: oidc_secret
    environment:
      MODE: "$MODE"
      DOMAIN: "$DOMAIN"
      SUBDOMAIN: "$SUBDOMAIN_GRAFANA"
      SUBDOMAIN_AUTHELIA: "$SUBDOMAIN_AUTHELIA"
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_logs:/var/log/grafana
      - type: bind
        source: /run/postgresql
        target: /run/postgresql
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  grafana_data:
    name: ${COMPOSE_PROJECT_NAME}.${MODE}.grafana.data
  grafana_logs:
    name: ${COMPOSE_PROJECT_NAME}.${MODE}.grafana.logs

configs:
  grafana_config:
    file: ../grafana.ini
    name: ${COMPOSE_PROJECT_NAME}.grafana.config

secrets:
  grafana_postgresql_password:
    environment: "${MODE}_POSTGRESQL_PASSWORD_GRAFANA"
  grafana_metrics_password:
    environment: "${MODE}_METRICS_PASSWORD_GRAFANA"
  grafana_oidc_secret:
    environment: "${MODE}_OIDC_SECRET_GRAFANA"
