services:
  grafana:
    extends:
      file: ${MODE}.yaml
      service: grafana
    build:
      context: ..
      args:
        GRAFANA_VERSION: "$VERSION_GRAFANA"
      tags:
        - "server_grafana:${VERSION_GRAFANA}"
    secrets:
      - source: grafana_postgresql_password
        target: postgresql_password
        mode: 0400
    environment:
      MODE: "$MODE"
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_logs:/var/log/grafana
      - /run/postgresql:/run/postgresql
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

secrets:
  grafana_postgresql_password:
    file: ./grafana/compose.yaml.d/secrets/${MODE}/postgresql_password

volumes:
  grafana_data:
    name: server_${MODE}_grafana_data
  grafana_logs:
    name: server_${MODE}_grafana_logs
