services:
  grafana:
    extends:
      file: ../../compose.yaml.d/compose.yaml
      service: common
    ports:
      - 3000:3000
    environment:
      GF_LOG_LEVEL: debug
      REDIRECTION_AUTHORITY_SUFFIX: "$LOCALHOST_REDIRECTION_SUFFIX"
    configs:
      - source: grafana_config
        target: /etc/grafana/grafana.ini
