services:
  grafana:
    extends:
      file: ../../compose.yaml.d/compose.yaml
      service: common
    ports:
      - 3000:3000
    environment:
      GF_LOG_LEVEL: debug
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      REDIRECTION_AUTHORITY_SUFFIX: "$LOCALHOST_REDIRECTION_SUFFIX"
        target: /etc/grafana/grafana.ini
