include:
  - grafana/compose.yaml.d/compose.yaml

services:
  grafana:
    environment:
      GF_SERVER_DOMAIN: "${SUBDOMAIN_GRAFANA}.${DOMAIN}"
      GF_SERVER_ROOT_URL: "https://$(domain)s"
    depends_on:
      - prometheus
