services:
  podman-exporter:
    extends:
      file: ${MODE}.yaml
      service: podman-exporter
    build:
      context: ..
      args:
        GO_BUILDER_VERSION: "${VERSION_BUILDER_GO}-alpine${VERSION_BUILDER_ALPINE}"
        PODMAN_EXPORTER_VERSION: "$VERSION_PODMAN_EXPORTER"
      tags:
        - "${COMPOSE_PROJECT_NAME}/podman-exporter:${VERSION_PODMAN_EXPORTER}"
    environment:
      CONTAINER_HOST: "unix:///run/podman/podman.sock"
    volumes:
      - type: bind
        source: "$XDG_RUNTIME_DIR/podman/podman.sock"
        target: /run/podman/podman.sock
    read_only: true
    security_opt:
      - no-new-privileges:true
      - label:disable
    cap_drop:
      - ALL
    userns_mode: keep-id:uid=65534
