services:
  authelia:
    extends:
      file: ${MODE}.yaml
      service: authelia
    build:
      context: ..
      args:
        AUTHELIA_VERSION: "$VERSION_AUTHELIA"
      tags:
        - "${COMPOSE_PROJECT_NAME}/authelia:${VERSION_AUTHELIA}"
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /run/secrets/jwt_secret
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /run/secrets/postgresql_password
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/storage_encryption_key
      AUTHELIA_SESSION_SECRET_FILE: /run/secrets/session_secret
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: /run/secrets/ldap_password
      X_AUTHELIA_CONFIG_FILTERS: expand-env,template
      SUBDOMAIN: "$SUBDOMAIN_AUTHELIA"
      SUBDOMAIN_GRAFANA: "$SUBDOMAIN_GRAFANA"
      DOMAIN: "$DOMAIN"
      MODE: "$MODE"
    volumes:
      - "authelia_notifications:/var/lib/authelia/notifications"
      - type: bind
        source: /run/postgresql
        target: /run/postgresql
      - type: tmpfs
        target: /app
    secrets:
      - source: authelia_jwt_secret
        target: jwt_secret
      - source: authelia_postgresql_password
        target: postgresql_password
      - source: authelia_storage_encryption_key
        target: storage_encryption_key
      - source: authelia_session_secret
        target: session_secret
      - source: authelia_ldap_password
        target: ldap_password
      - source: authelia_oidc_private_key
        target: oidc_private_key
      - source: authelia_oidc_secret_hash_grafana
        target: oidc_secret_hash_grafana
    # network_mode: "slirp4netns:allow_host_loopback=true"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID

volumes:
  authelia_notifications:
    name: ${COMPOSE_PROJECT_NAME}.${MODE}.authelia.notifications

secrets:
  authelia_jwt_secret:
    environment: "${MODE}_AUTHELIA_JWT_SECRET"
  authelia_postgresql_password:
    environment: "${MODE}_POSTGRESQL_PASSWORD_AUTHELIA"
  authelia_storage_encryption_key:
    environment: "${MODE}_AUTHELIA_STORAGE_ENCRYPTION_KEY"
  authelia_session_secret:
    environment: "${MODE}_AUTHELIA_SESSION_SECRET"
  authelia_ldap_password:
    environment: "${MODE}_LDAP_PASSWORD_AUTHELIA"
  authelia_oidc_private_key:
    file: "./secrets/${MODE}/private.pem"
  authelia_oidc_secret_hash_grafana:
    environment: "${MODE}_OIDC_SECRET_HASH_GRAFANA"

configs:
  authelia_config:
    file: ../configuration.yml
    name: ${COMPOSE_PROJECT_NAME}.authelia.config
