services:
  authelia:
    extends:
      file: ${MODE}.yaml
      service: authelia
    build:
      context: ..
      args:
        AUTHELIA_VERSION: "$VERSION_AUTHELIA"
      tags:
        - "${COMPOSE_PROJECT_NAME}/authelia:${VERSION_AUTHELIA}"
    environment:
      AUTHELIA_JWT_SECRET_FILE: /run/secrets/jwt_secret
      AUTHELIA_STORAGE_POSTGRES_DATABASE: "${MODE}_authelia"
      AUTHELIA_STORAGE_POSTGRES_USERNAME: "${MODE}_authelia"
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /run/secrets/postgresql_password
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/storage_encryption_key
      AUTHELIA_SESSION_SECRET_FILE: /run/secrets/session_secret
    volumes:
      - authelia_logs:/var/log
      - type: bind
        source: /run/postgresql
        target: /run/postgresql
    secrets:
      - source: authelia_jwt_secret
        target: jwt_secret
      - source: authelia_postgresql_password
        target: postgresql_password
      - source: authelia_storage_encryption_key
        target: storage_encryption_key
      - source: authelia_session_secret
        target: session_secret
    # network_mode: "slirp4netns:allow_host_loopback=true"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETGID

secrets:
  authelia_jwt_secret:
    file: ./authelia/compose.yaml.d/secrets/${MODE}/jwt_secret
  authelia_postgresql_password:
    file: ./authelia/compose.yaml.d/secrets/${MODE}/postgresql_password
  authelia_storage_encryption_key:
    file: ./authelia/compose.yaml.d/secrets/${MODE}/storage_encryption_key
  authelia_session_secret:
    file: ./authelia/compose.yaml.d/secrets/${MODE}/session_secret

volumes:
  authelia_logs:
    name: server_${MODE}_authelia_logs
