include:
  - authelia/compose.yaml.d/compose.yaml

services:
  authelia:
    environment:
      AUTHELIA_LOG_LEVEL: debug
      AUTHELIA_DEFAULT_REDIRECTION_URL: "https://${SUBDOMAIN_AUTHELIA}.localhost"
      AUTHELIA_SESSION_DOMAIN: "https://${SUBDOMAIN_AUTHELIA}.localhost"
    volumes:
      - ../configuration.yml:/config/configuration.yml:ro
