services:
  authelia:
    extends:
      file: ../../compose.yaml.d/compose.yaml
      service: common
    environment:
      AUTHELIA_LOG_LEVEL: debug
    volumes:
      - ./authelia/configuration.yml:/config/configuration.yml:ro
