services:
  authelia:
    extends:
      file: ../../compose.yaml.d/compose.yaml
      service: common
    environment:
      AUTHELIA_LOG_LEVEL: debug
      AUTHELIA_DEFAULT_REDIRECTION_URL: "https://${SUBDOMAIN_AUTHELIA}.${LOCALHOST:-localhost}"
      AUTHELIA_SESSION_DOMAIN: "https://${SUBDOMAIN_AUTHELIA}.${LOCALHOST:-localhost}"
    volumes:
      - ./authelia/configuration.yml:/config/configuration.yml:ro
