services:
  authelia:
    extends:
      file: ../../compose.yaml.d/compose.yaml
      service: common
    environment:
      AUTHELIA_LOG_LEVEL: debug
    configs:
      - source: authelia_config
        target: /etc/authelia.yml
    ports:
      - 9091:9091
      - 9959:9959
