include:
  - authelia/compose.yaml.d/compose.yaml

services:
  authelia:
    environment:
      AUTHELIA_DEFAULT_REDIRECTION_URL: "${SUBDOMAIN_AUTHELIA}.${DOMAIN}"
      AUTHELIA_SESSION_DOMAIN: "${SUBDOMAIN_AUTHELIA}.${DOMAIN}"
    depends_on:
      - lldap
