services:
  authelia:
    extends:
      file: ../../compose.yaml.d/compose.yaml
      service: common
    environment:
      LDAP_BASE_DN: "dc=${DOMAIN_NAME},dc=${TLD}"
    depends_on:
      - lldap
