services:
  crowdsec:
    extends:
      file: ${MODE}.yaml
      service: crowdsec 
    build:
      context: ..
      args:
        CROWDSEC_VERSION: "$VERSION_CROWDSEC"
      tags:
        - "${COMPOSE_PROJECT_NAME}/crowdsec:${VERSION_CROWDSEC}"
    environment:
      COLLECTIONS: >-
        crowdsecurity/caddy
        crowdsecurity/sshd
        crowdsecurity/whitelist-good-actors
      DISABLE_PARSERS: >-
        crowdsecurity/cri-logs
        crowdsecurity/docker-logs
        crowdsecurity/geoip-enrich
      BOUNCER_KEY_firewall: "$CROWDSEC_BOUNCER_KEY_FIREWALL"
      MODE: "$MODE"
    volumes:
      - caddy_logs:/run/log/caddy:ro
      - crowdsec_config:/etc/crowdsec
      - crowdsec_data:/var/lib/crowdsec/data
      - crowdsec_logs:/var/log
      - type: bind
        source: /var/log/sshd.log
        target: /run/log/host/sshd.log
        read_only: true
      - type: bind
        source: /run/postgresql
        target: /run/postgresql
    ports:
      - 127.0.0.1:8080:8080
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

configs:
  crowdsec_local_config:
    file: ../config.yaml.local
    name: ${COMPOSE_PROJECT_NAME}.crowdsec.local_config

volumes:
  crowdsec_config:
    name: ${COMPOSE_PROJECT_NAME}.${MODE}.crowdsec.config
  crowdsec_data:
    name: ${COMPOSE_PROJECT_NAME}.${MODE}.crowdsec.data
  crowdsec_logs:
    name: ${COMPOSE_PROJECT_NAME}.${MODE}.crowdsec.logs
