services:
  crowdsec:
    extends:
      file: ${MODE}.yaml
      service: crowdsec 
    build:
      context: ..
      args:
        CROWDSEC_VERSION: "$VERSION_CROWDSEC"
      tags:
        - "server_crowdsec:${VERSION_CROWDSEC}"
    environment:
      COLLECTIONS: >-
        crowdsecurity/caddy
        crowdsecurity/sshd
      DISABLE_PARSERS: >-
        crowdsecurity/cri-logs
        crowdsecurity/docker-logs
        crowdsecurity/geoip-enrich
      BOUNCER_KEY_caddy: "$CROWDSEC_BOUNCER_KEY_CADDY"
      BOUNCER_KEY_firewall: "$CROWDSEC_BOUNCER_KEY_FIREWALL"
      MODE: "$MODE"
    volumes:
      - caddy_logs:/run/log/caddy:ro
      - /var/log/sshd.log:/run/log/host/sshd.log:ro
      - crowdsec_config:/etc/crowdsec
      - crowdsec_data:/var/lib/crowdsec/data
      - crowdsec_logs:/var/log
      - /run/postgresql:/run/postgresql
    ports:
      - 127.0.0.1:8080:8080
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    group_add:
      - keep-groups

volumes:
  crowdsec_config:
    name: server_${MODE}_crowdsec_config
  crowdsec_data:
    name: server_${MODE}_crowdsec_data
  crowdsec_logs:
    name: server_${MODE}_crowdsec_logs
