services:
  crowdsec:
    extends:
      file: ../../compose.yaml.d/compose.yaml
      service: common
    environment:
      POSTGRESQL_PASSWORD: "$production_POSTGRESQL_PASSWORD_CROWDSEC"
      BOUNCER_KEY_caddy: "$production_CROWDSEC_BOUNCER_KEY_CADDY"
