services:
  lldap:
    extends:
      file: ${MODE}.yaml
      service: lldap
    build:
      context: ..
      args:
        LLDAP_VERSION: "$VERSION_LLDAP"
      tags:
        - "${COMPOSE_PROJECT_NAME}/lldap:${VERSION_LLDAP}"
    volumes:
      - lldap_data:/data
      - type: bind
        source: /run/postgresql
        target: /run/postgresql
      - type: tmpfs
        target: /app
    secrets:
      - source: lldap_jwt_secret
        target: jwt_secret
      - source: lldap_ldap_admin_password
        target: ldap_admin_password
    environment:
      LLDAP_JWT_SECRET_FILE: /run/secrets/jwt_secret
      LLDAP_LDAP_USER_PASS_FILE: /run/secrets/ldap_admin_password
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  lldap_data:
    name: ${COMPOSE_PROJECT_NAME}.${MODE}.lldap.data

secrets:
  lldap_jwt_secret:
    environment: "${MODE}_LLDAP_JWT_SECRET"
  lldap_ldap_admin_password:
    environment: "${MODE}_LDAP_ADMIN_PASSWORD_LLDAP"
