services:
  lldap:
    extends:
      file: ${MODE}.yaml
      service: lldap
    build:
      context: ..
      args:
        LLDAP_VERSION: "$VERSION_LLDAP"
      tags:
        - "server_lldap:${VERSION_LLDAP}"
    volumes:
      - lldap_data:/data
      - /run/postgresql:/run/postgresql
      - type: tmpfs
        target: /app
    environment:
      LLDAP_JWT_SECRET_FILE: /run/secrets/jwt_secret
      LLDAP_LDAP_USER_PASS_FILE: /run/secrets/ldap_user_pass
      LLDAP_DATABASE_URL: "postgres://${MODE}_lldap:${POSTGRESQL_PASSWORD_LLDAP}@%2Frun%2Fpostgresql/${MODE}_lldap"
    secrets:
      - source: lldap_jwt_secret
        target: jwt_secret
        mode: 0400
      - source: lldap_ldap_user_pass
        target: ldap_user_pass
        mode: 0400
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID

secrets:
  lldap_jwt_secret:
    file: ./lldap/compose.yaml.d/secrets/jwt_secret
  lldap_ldap_user_pass:
    file: ./lldap/compose.yaml.d/secrets/ldap_user_pass

volumes:
  lldap_data:
    name: server_${MODE}_lldap_data
