services:
  lldap:
    extends:
      file: ../../compose.yaml.d/compose.yaml
      service: common
    environment:
      LLDAP_VERBOSE: "true"
      LLDAP_HTTP_URL: "https://${SUBDOMAIN_LLDAP}.${LOCALHOST:-localhost}"
