services:
  lldap:
    extends:
      file: ../../compose.yaml.d/compose.yaml
      service: common
    environment:
      LLDAP_HTTP_URL: "https://${SUBDOMAIN_LLDAP}.${DOMAIN}"
      LLDAP_DATABASE_URL: "postgres://${MODE}_lldap:${production_POSTGRESQL_PASSWORD_LLDAP}@%2Frun%2Fpostgresql/${MODE}_lldap"
      LLDAP_LDAP_BASE_DN: "dc=${DOMAIN_NAME},dc=${TLD}"
