services:
  prometheus:
    extends:
      file: ${MODE}.yaml
      service: prometheus
    build:
      context: ..
      args:
        PROMETHEUS_VERSION: "$VERSION_PROMETHEUS"
      tags:
        - "server_prometheus:${VERSION_PROMETHEUS}"
    volumes:
      - prometheus_data:/prometheus
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  prometheus_data:
    name: server_${MODE}_prometheus_data
