x-restart: &restart
  {}

x-healthcheck: &healthcheck
  {}

services:
  prometheus:
    <<: *restart
    build:
      context: prometheus
      args:
        PROMETHEUS_VERSION: "$VERSION_PROMETHEUS"
      tags:
        - "server_prometheus:${VERSION_PROMETHEUS}"
    volumes:
      - prometheus_data:/prometheus
    healthcheck:
      <<: *healthcheck
      test: wget -q --spider localhost:9090/-/healthy || exit 1
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  prometheus_data:
    name: server_${MODE}_prometheus_data
