services:
  prometheus:
    extends:
      file: ${MODE}.yaml
      service: prometheus
    build:
      context: ..
      args:
        PROMETHEUS_VERSION: "$VERSION_PROMETHEUS"
      tags:
        - "${COMPOSE_PROJECT_NAME}/prometheus:${VERSION_PROMETHEUS}"
    volumes:
      - prometheus_data:/prometheus
    secrets:
      - source: caddy_metrics_password
        target: metrics_password_caddy
      - source: grafana_metrics_password
        target: metrics_password_grafana
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

secrets:
  caddy_metrics_password:
    environment: "${MODE}_METRICS_PASSWORD_CADDY"
  grafana_metrics_password:
    environment: "${MODE}_METRICS_PASSWORD_GRAFANA"

volumes:
  prometheus_data:
    name: ${COMPOSE_PROJECT_NAME}.${MODE}.prometheus.data
