include:
- ../../caddy/compose.yaml.d/compose.yaml

services:
  tor:
    extends:
      file: ${MODE}.yaml
      service: tor
    build:
      context: ..
      args:
        TOR_VERSION: "$VERSION_TOR"
        ALPINE_VERSION: "$VERSION_BUILDER_ALPINE"
        LIBEVENT_VERSION: "$VERSION_BUILDER_LIBEVENT"
        OPENSSL_VERSION: "$VERSION_BUILDER_OPENSSL"
        ZLIB_VERSION: "$VERSION_BUILDER_ZLIB"
        DISTROLESS_SUFFIX: "$VERSION_DISTROLESS_SUFFIX"
        CFLAGS: "$CFLAGS"
        LDFLAGS: "$LDFLAGS"
      tags:
        - "${COMPOSE_PROJECT_NAME}/tor:${VERSION_TOR}"
    volumes:
      - tor_data:/var/lib/tor
      - caddy_tor_socket:/run/tor
    secrets:
      - source: tor_public_key
        target: hs_ed25519_public_key
      - source: tor_secret_key
        target: hs_ed25519_secret_key
      - source: tor_hostname
        target: hostname
    ports:
      - 9050:9050
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

volumes:
  tor_data:
    name: ${COMPOSE_PROJECT_NAME}.${MODE}.tor.data

configs:
  tor_torrc:
    file: ../torrc
    name: ${COMPOSE_PROJECT_NAME}.tor.torrc

secrets:
  tor_public_key:
    file: ./secrets/hs_ed25519_public_key
    name: ${COMPOSE_PROJECT_NAME}.tor.public_key
  tor_secret_key:
    file: ./secrets/hs_ed25519_secret_key
    name: ${COMPOSE_PROJECT_NAME}.tor.secret_key
  tor_hostname:
    environment: "TOR_DOMAIN"
    name: ${COMPOSE_PROJECT_NAME}.tor.hostname
