services:
  tor:
    extends:
      file: ../../compose.yaml.d/compose.yaml
      service: common
    configs:
      - source: tor_torrc
        target: /etc/tor/torrc

    command: ["--Log", "debug syslog"]
