session:
  name: "authelia_${MODE}_session"
  cookies:
  - domain: "${SUBDOMAIN}.${DOMAIN}"
    authelia_url: "https://${SUBDOMAIN}.${DOMAIN}${REDIRECTION_AUTHORITY_SUFFIX}"
  same_site: strict

regulation:
  max_retries: 5

password_policy:
  zxcvbn:
    enabled: true
    min_score: 4

totp:
  period: 15

telemetry:
  metrics:
    enabled: true

authentication_backend:
  ldap:
    implementation: custom
    address: ldap://lldap:3890
    base_dn: "$LDAP_BASE_DN"
    user: "uid=authelia,ou=people,${LDAP_BASE_DN}"
    additional_users_dn: ou=people
    users_filter: "(&(|({username_attribute}={input})(mail_attribute={input}))(objectClass=person)(memberOf=cn=humans,ou=groups,${LDAP_BASE_DN}))"
    additional_groups_dn: ou=groups
    groups_filter: "(member={dn})"
    attributes:
      username: uid

access_control:
  default_policy: two_factor

storage:
  postgres:
    address: unix:///run/postgresql
    database: "${MODE}_authelia"
    username: "${MODE}_authelia"

notifier:
  filesystem:
    filename: /var/lib/authelia/notifications/notifications.txt
  # smtp:

identity_providers:
  oidc:
    issuer_private_keys:
      - key: |
          {{- fileContent "/run/secrets/oidc_private_key" | nindent 10 }}
    clients:
      - id: grafana
        description: Grafana
        secret: {{ fileContent "/run/secrets/oidc_secret_hash_grafana" }}
        redirect_uris:
          - "https://${SUBDOMAIN_GRAFANA}.${DOMAIN}${REDIRECTION_AUTHORITY_SUFFIX}/login/generic_oauth"
        scopes:
          - openid
          - groups
          - profile
        pkce_challenge_method: S256

theme: auto
