
theme: dark

log:
  file_path: /var/log/authelia.log
session:
  name: "authelia_${MODE}_session"
  cookies:
  - domain: "${SUBDOMAIN}.${DOMAIN}"
    authelia_url: "https://${SUBDOMAIN}.${DOMAIN}${REDIRECTION_AUTHORITY_SUFFIX}"

regulation:
  max_retries: 5

password_policy:
  zxcvbn:
    enabled: true
    min_score: 4

totp:
  period: 15

telemetry:
  metrics:
    enabled: true

authentication_backend:
  ldap:
    implemenation: custom
    url: ldap://lldap:3890

# access_control:
#   default_policy: deny
#   rules:
#     - domain: public.example.com
#       policy: bypass
#     - domain: traefik.example.com
#       policy: one_factor
#     - domain: secure.example.com
#       policy: two_factor

storage:
  postgres:
    host: /var/run/postgresql

notifier:
  filesystem:
    filename: /config/notification.txt
  # smtp:



...

