services:
  mail-server:
    extends:
      file: ${MODE}.yaml
      service: mail-server
    build:
      context: ..
      args:
        MAIL_SERVER_VERSION: "$VERSION_MAIL_SERVER"
        DISTROLESS_SUFFIX: "$VERSION_DISTROLESS_SUFFIX"
        MUSLRUST_VERSION: "$VERSION_BUILDER_MUSLRUST"
        ALPINE_VERSION: "$VERSION_BUILDER_ALPINE"
        RUSTFLAGS: "$RUSTFLAGS"
      tags:
        - "${COMPOSE_PROJECT_NAME}/mail-server:${VERSION_MAIL_SERVER}"
    ports:
      - 25:25
      - 465:465
      - 993:993
    secrets:
      - source: mail_server_metrics_password
        target: metrics_password
    environment:
      DOMAIN: "$DOMAIN"
      MX_SUBDOMAIN: "$MX_SUBDOMAIN"
    volumes:
      - mail_server_data:/opt/stalwart-mail
      - type: bind
        source: ../etc/certs
        target: /opt/stalwart-mail/etc/certs
        read_only: true
      - type: bind
        source: /run/postgresql
        target: /run/postgresql
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

volumes:
  mail_server_data:
    name: ${COMPOSE_PROJECT_NAME}.${MODE}.mail-server.data

secrets:
  mail_server_metrics_password:
    environment: "${MODE}_METRICS_PASSWORD_MAIL_SERVER"
