version: 3

name: server

x-restart: &restart
  {}

x-healthcheck: &healthcheck
  healthcheck:
    start_period: 30s
    timeout: 5s

services:
  caddy:
    <<: *restart
    build:
      context: caddy
      args:
        CADDY_VERSION: "$VERSION_CADDY"
      tags:
        - "server_caddy:${VERSION_CADDY}"
    environment:
      CROWDSEC_BOUNCER_KEY: "$CROWDSEC_BOUNCER_KEY_CADDY"
      SUBDOMAIN_GRAFANA: "$SUBDOMAIN_GRAFANA"
      POSTGRESQL_PASSWORD: "$POSTGRESQL_PASSWORD_CADDY"
    volumes:
      - caddy_logs:/var/log/caddy
      - caddy_data:/data
      - caddy_pseudo_config:/config
    expose:
      - 2019
    ports:
      - 50080:80
      - 50443:443
    # read_only: true
    network_mode: "slirp4netns:allow_host_loopback=true"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

  # TODO: setup syslog server
  crowdsec:
    <<: *restart
    <<: *healthcheck
    build:
      context: crowdsec
      args:
        CROWDSEC_VERSION: "$VERSION_CROWDSEC"
      tags:
        - "server_crowdsec:${VERSION_CROWDSEC}"
    environment:
      COLLECTIONS: >-
        crowdsecurity/caddy
        crowdsecurity/sshd
      DISABLE_PARSERS: >-
        crowdsecurity/cri-logs
        crowdsecurity/docker-logs
        crowdsecurity/geoip-enrich
      BOUNCER_KEY_caddy: "$CROWDSEC_BOUNCER_KEY_CADDY"
      POSTGRESQL_PASSWORD: "$POSTGRESQL_PASSWORD_CROWDSEC"
    secrets:
      - source: crowdsec_bouncer_key_firewall
        target: bouncer_key_firewall
        mode: 0400

    ports:
      - 127.0.0.1:8080:8080
    expose:
      - 6060
    volumes:
      - caddy_logs:/run/log/caddy:ro
      - /var/log/sshd.log:/run/log/host/sshd.log:ro
      - crowdsec_config:/etc/crowdsec
      - crowdsec_data:/var/lib/crowdsec/data
      - crowdsec_logs:/var/log
      - /run/postgresql:/var/run/postgresql
    healthcheck:
      test: wget -q --spider localhost:8080/health || exit 1
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    group_add:
      - keep-groups

  prometheus:
    <<: *restart
    <<: *healthcheck
    build:
      context: prometheus
      args:
        PROMETHEUS_VERSION: "$VERSION_PROMETHEUS"
      tags:
        - "server_prometheus:${VERSION_PROMETHEUS}"
    volumes:
      - prometheus_data:/prometheus
    healthcheck:
      test: wget -q --spider localhost:9090/-/healthy || exit 1
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  grafana:
    <<: *restart
    <<: *healthcheck
    build:
      context: grafana
      args:
        GRAFANA_VERSION: "$VERSION_GRAFANA"
      tags:
        - "server_grafana:${VERSION_GRAFANA}"
    secrets:
      - source: postgresql_password_grafana
        target: postgresql_password
        mode: 0400
    expose:
      - 3000
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_logs:/var/log/grafana
      - /run/postgresql:/var/run/postgresql
    healthcheck:
      test: wget -q --spider localhost:3000/api/health || exit 1
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  # radicale:
  #   build:
  #     context: radicale
  #     args:
  #       RADICALE_VERSION: "$RADICALE_VERSION"
  #   environment:
  #     TAKE_FILE_OWNERSHIP: false
  #   expose:
  #     - 5232
  #   init: true
  #   read_only: true
  #   security_opt:
  #     - no-new-privileges:true
  #   cap_drop:
  #     - ALL
  #   cap_add:
  #     - SETUID
  #     - SETGID
  #     - CHOWN
  #     - KILL
  #   healthcheck:
  #     test: curl -o /dev/null -f http://127.0.0.1:5232 || exit
  #     interval: 30s
  #     retries: 3
  #   volumes:
  #     - radicale_data:/data

  # ejabberd:
  #   build:
  #     context: ejabberd
  #     args:
  #       EJABBERD_VERSION: "$EJABBERD_VERSION"
  #   expose:
  #     - 5222
  #     - 5269
  #     - 5280
  #     - 5443
  #     - 1883
  #   volumes:
  #     - ejabberd_data:/home/ejabberd/database
  #     - ejabberd_logs:/home/ejabberd/logs
  #     - ejabberd_uploads:/home/ejabberd/upload


volumes:

  caddy_logs:
  caddy_data:
  caddy_pseudo_config:

  crowdsec_config:
  crowdsec_data:
  crowdsec_logs:

  prometheus_data:

  grafana_data:
  grafana_logs:

  authelia_config:

  lldap_data:

  # radicale_data:

  # ejabberd_data:
  # ejabberd_logs:
  # ejabberd_uploads:

secrets:
  crowdsec_bouncer_key_firewall:
    file: ./secrets/crowdsec_bouncer_api_keys/firewall
  postgresql_password_grafana:
    file: ./secrets/postgresql_passwords/grafana
  postgresql_password_authelia:
    file: ./secrets/postgresql_passwords/authelia
