version: 3

name: server

x-restart: &restart
  {}

services:
  caddy:
    <<: *restart
    build:
      context: caddy
      args:
        CADDY_VERSION: "$CADDY_VERSION"
      tags:
        - "server_caddy:${CADDY_VERSION}"
    environment:
      CROWDSEC_BOUNCER_API_KEY: "$BOUNCER_KEY_caddy"
    volumes:
      - caddy_logs:/var/log/caddy
      - caddy_data:/data
      - caddy_pseudo_config:/config
    ports:
      - 50080:80
      - 50443:443
    depends_on:
      crowdsec:
        restart: false
        condition: service_healthy
        required: false
    # read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

  # TODO: setup syslog server
  crowdsec:
    <<: *restart
    build:
      context: crowdsec
      args:
        CROWDSEC_VERSION: "$CROWDSEC_VERSION"
      tags:
        - "server_crowdsec:${CROWDSEC_VERSION}"
    environment:
      COLLECTIONS: >-
        crowdsecurity/caddy
      BOUNCER_KEY_caddy: "$BOUNCER_KEY_caddy"
      BOUNCER_KEY_firewall: "$BOUNCER_KEY_firewall"
      GID: 1000
    expose:
      - 8080
    volumes:
      - caddy_logs:/var/log/caddy:ro
      - /var/log/messages:/var/log/host/messages:ro
      - crowdsec_config:/etc/crowdsec
      - crowdsec_data:/var/lib/crowdsec/data
    init: true
    healthcheck:
      test: wget -q --spider localhost:8080/health
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
    group_add:
      - keep-groups


  # radicale:
  #   build:
  #     context: radicale
  #     args:
  #       RADICALE_VERSION: "$RADICALE_VERSION"
  #   environment:
  #     TAKE_FILE_OWNERSHIP: false
  #   expose:
  #     - 5232
  #   init: true
  #   read_only: true
  #   security_opt:
  #     - no-new-privileges:true
  #   cap_drop:
  #     - ALL
  #   cap_add:
  #     - SETUID
  #     - SETGID
  #     - CHOWN
  #     - KILL
  #   healthcheck:
  #     test: curl -o /dev/null -f http://127.0.0.1:5232 || exit
  #     interval: 30s
  #     retries: 3
  #   volumes:
  #     - radicale_data:/data

  # ejabberd:
  #   build:
  #     context: ejabberd
  #     args:
  #       EJABBERD_VERSION: "$EJABBERD_VERSION"
  #   expose:
  #     - 5222
  #     - 5269
  #     - 5280
  #     - 5443
  #     - 1883
  #   volumes:
  #     - ejabberd_data:/home/ejabberd/database
  #     - ejabberd_logs:/home/ejabberd/logs
  #     - ejabberd_uploads:/home/ejabberd/upload


volumes:

  caddy_logs:
  caddy_data:
  caddy_pseudo_config:

  crowdsec_config:
  crowdsec_data:

  # radicale_data:

  # ejabberd_data:
  # ejabberd_logs:
  # ejabberd_uploads:
