version: 3

name: server

x-restart: &restart
  {}

services:
  caddy:
    <<: *restart
    build:
      context: caddy
      args:
        CADDY_VERSION: "$CADDY_VERSION"
      tags:
        - "server_caddy:${CADDY_VERSION}"
    environment:
      CROWDSEC_BOUNCER_API_KEY: "$BOUNCER_KEY_caddy"
      GRAFANA_SUBDOMAIN: "$GRAFANA_SUBDOMAIN"
    volumes:
      - caddy_logs:/var/log/caddy
      - caddy_data:/data
      - caddy_pseudo_config:/config
    expose:
      - 2019
    ports:
      - 50080:80
      - 50443:443
    # read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

  # TODO: setup syslog server
  crowdsec:
    <<: *restart
    build:
      context: crowdsec
      args:
        CROWDSEC_VERSION: "$CROWDSEC_VERSION"
      tags:
        - "server_crowdsec:${CROWDSEC_VERSION}"
    environment:
      COLLECTIONS: >-
        crowdsecurity/caddy
        crowdsecurity/sshd
      DISABLE_PARSERS: >-
        crowdsecurity/cri-logs
        crowdsecurity/docker-logs
        crowdsecurity/geoip-enrich
      BOUNCER_KEY_caddy: "$BOUNCER_KEY_caddy"
      BOUNCER_KEY_firewall: "$BOUNCER_KEY_firewall"
    ports:
      - 127.0.0.1:8080:8080
    expose:
      - 6060
    volumes:
      - caddy_logs:/run/log/caddy:ro
      - /var/log/sshd.log:/run/log/host/sshd.log:ro
      - crowdsec_config:/etc/crowdsec
      - crowdsec_data:/var/lib/crowdsec/data
      - crowdsec_logs:/var/log
    healthcheck:
      test: wget -q --spider localhost:8080/health
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
    group_add:
      - keep-groups

  prometheus:
    <<: *restart
    build:
      context: prometheus
      args:
        PROMETHEUS_VERSION: "$PROMETHEUS_VERSION"
      tags:
        - "server_prometheus:${PROMETHEUS_VERSION}"
    volumes:
      - prometheus_data:/prometheus
    healthcheck:
      test: wget -q --spider localhost:9090/-/healthy
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  grafana:
    <<: *restart
    build:
      context: grafana
      args:
        GRAFANA_VERSION: "$GRAFANA_VERSION"
      tags:
        - "server_grafana:${GRAFANA_VERSION}"
    expose:
      - 3000
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_logs:/var/log/grafana
    healthcheck:
      test: wget -q --spider localhost:3000/api/health
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  # radicale:
  #   build:
  #     context: radicale
  #     args:
  #       RADICALE_VERSION: "$RADICALE_VERSION"
  #   environment:
  #     TAKE_FILE_OWNERSHIP: false
  #   expose:
  #     - 5232
  #   init: true
  #   read_only: true
  #   security_opt:
  #     - no-new-privileges:true
  #   cap_drop:
  #     - ALL
  #   cap_add:
  #     - SETUID
  #     - SETGID
  #     - CHOWN
  #     - KILL
  #   healthcheck:
  #     test: curl -o /dev/null -f http://127.0.0.1:5232 || exit
  #     interval: 30s
  #     retries: 3
  #   volumes:
  #     - radicale_data:/data

  # ejabberd:
  #   build:
  #     context: ejabberd
  #     args:
  #       EJABBERD_VERSION: "$EJABBERD_VERSION"
  #   expose:
  #     - 5222
  #     - 5269
  #     - 5280
  #     - 5443
  #     - 1883
  #   volumes:
  #     - ejabberd_data:/home/ejabberd/database
  #     - ejabberd_logs:/home/ejabberd/logs
  #     - ejabberd_uploads:/home/ejabberd/upload


volumes:

  caddy_logs:
  caddy_data:
  caddy_pseudo_config:

  crowdsec_config:
  crowdsec_data:
  crowdsec_logs:

  prometheus_data:

  grafana_data:
  grafana_logs:

  # radicale_data:

  # ejabberd_data:
  # ejabberd_logs:
  # ejabberd_uploads:
