x-restart: &restart
  restart: unless-stopped

services:
  caddy:
    environment:
      DOMAIN: "$DOMAIN"
      EMAIL: "$EMAIL"
      CADDY_EXTRA_DIRECTIVES: "import production"
    depends_on:
      crowdsec:
        restart: false
        condition: service_healthy
        required: false
