x-restart: &restart
  restart: unless-stopped

services:
  caddy:
    environment:
      DOMAIN: "$DOMAIN"
      EMAIL: "$EMAIL"
      EXTRA_DIRECTIVES: "import production"
    depends_on:
      crowdsec:
        condition: service_healthy
      authelia:
        required: true

  grafana:
    environment:
      GF_SERVER_DOMAIN: "${SUBDOMAIN_GRAFANA}.${DOMAIN}"
    depends_on:
      prometheus:
        restart: false
        condition: service_healthy

  authelia:
    environment:
      AUTHELIA_DEFAULT_REDIRECTION_URL: "${SUBDOMAIN_AUTHELIA}.${DOMAIN}"
      AUTHELIA_SESSION_DOMAIN: "${SUBDOMAIN_AUTHELIA}.${DOMAIN}"

