x-restart: &restart
  restart: unless-stopped

services:
  caddy:
    environment:
      DOMAIN: "$DOMAIN"
      EMAIL: "$EMAIL"
      CADDY_EXTRA_DIRECTIVES: "import production"
    depends_on:
      crowdsec:
        restart: false
        condition: service_healthy

  grafana:
    environment:
      GF_SERVER_DOMAIN: "${GRAFANA_SUBDOMAIN}.${DOMAIN}"
    depends_on:
      prometheus:
        restart: false
        condition: service_healthy
