#############################################
# In-Memory Directory configuration
#############################################

[directory."memory"]
type = "memory"
disable = true

[directory."memory".options]
catch-all = true
#catch-all = { map = "(.+)@(.+)$", to = "info@${2}" }
subaddressing = true
#subaddressing = { map = "^([^.]+)\.([^.]+)@(.+)$", to = "${2}@${3}" }

[[directory."memory".principals]]
name = "admin"
type = "admin"
description = "Superuser"
secret = "changeme"
email = ["postmaster@%{DOMAIN}%"]

[[directory."memory".principals]]
name = "john"
type = "individual"
description = "John Doe"
secret = "12345"
email = ["john@%{DOMAIN}%", "jdoe@%{DOMAIN}%", "john.doe@%{DOMAIN}%"]
email-list = ["info@%{DOMAIN}%"]
member-of = ["sales"]

[[directory."memory".principals]]
name = "jane"
type = "individual"
description = "Jane Doe"
secret = "abcde"
email = ["jane@%{DOMAIN}%", "jane.doe@%{DOMAIN}%"]
email-list = ["info@%{DOMAIN}%"]
member-of = ["sales", "support"]

[[directory."memory".principals]]
name = "bill"
type = "individual"
description = "Bill Foobar"
secret = "$2y$05$bvIG6Nmid91Mu9RcmmWZfO5HJIMCT8riNW0hEp8f6/FuA2/mHZFpe"
quota = 50000000
email = ["bill@%{DOMAIN}%", "bill.foobar@%{DOMAIN}%"]
email-list = ["info@%{DOMAIN}%"]

[[directory."memory".principals]]
name = "sales"
type = "group"
description = "Sales Team"

[[directory."memory".principals]]
name = "support"
type = "group"
description = "Support Team"
