#############################################
# JMAP authentication & session configuration
#############################################

[jmap.session.cache]
ttl = "1h"
size = 100

[jmap.session.purge]
frequency = "15 * *"
