#############################################
# JMAP OAuth server configuration
#############################################

[oauth]
key = "5gRFtaTQ5FtkSOqSUbEaHG1hZjlbe7bkERerx5r9bOCqNXQmMy85V1TxMHLVQteA"

[oauth.auth]
max-attempts = 3

[oauth.expiry]
user-code = "30m"
auth-code = "10m"
token = "1h"
refresh-token = "30d"
refresh-token-renew = "4d"

[oauth.cache]
size = 128
