
#############################################
# SMTP DMARC, DKIM, SPF, ARC & IpRev
#############################################

[auth.iprev]
verify = [ { if = "listener = 'smtp'", then = "relaxed" }, 
           { else = "disable" } ]

[auth.dkim]
verify = "relaxed"
sign = [ { if = "listener != 'smtp'", then = "['rsa']" }, 
         { else = false } ]

[auth.spf.verify]
ehlo = [ { if = "listener = 'smtp'", then = "relaxed" }, 
         { else = "disable" } ]
mail-from = [ { if = "listener = 'smtp'", then = "relaxed" }, 
              { else = "disable" } ]

[auth.arc]
verify = "relaxed"
seal = "['rsa']"

[auth.dmarc]
verify = [ { if = "listener = 'smtp'", then = "relaxed" }, 
           { else = "disable" } ]

