#############################################
# SMTP DKIM & ARC signatures
#############################################

[signature."rsa"]
#public-key = "file://%{BASE_PATH}%/etc/dkim/%{DOMAIN}%.cert"
private-key = "file://%{BASE_PATH}%/etc/dkim/%{DOMAIN}%.key"
domain = "%{DOMAIN}%"
selector = "stalwart"
headers = ["From", "To", "Date", "Subject", "Message-ID"]
algorithm = "rsa-sha256"
canonicalization = "relaxed/relaxed"
#expire = "10d"
#third-party = ""
#third-party-algo = ""
#auid = ""
set-body-length = false
report = true
