services:
  caddy:
    extends:
      file: ${MODE}.yaml
      service: caddy
    build:
      context: ..
      args:
        CADDY_VERSION: "$VERSION_CADDY"
        CROWDSEC_BOUNCER_VERSION: "$VERSION_CADDY_CROWDSEC_BOUNCER"
        DNS_IP_RANGE_VERSION: "$VERSION_CADDY_DNS_IP_RANGE"
      tags:
        - "${COMPOSE_PROJECT_NAME}/caddy:${VERSION_CADDY}"
    environment:
      MODE: "$MODE"
      DOMAIN: "$DOMAIN"
      TOR_DOMAIN: "$TOR_DOMAIN"
      MX_SUBDOMAIN: "$MX_SUBDOMAIN"
      SUBDOMAIN_GRAFANA: "$SUBDOMAIN_GRAFANA"
      SUBDOMAIN_AUTHELIA: "$SUBDOMAIN_AUTHELIA"
      SUBDOMAIN_LLDAP: "$SUBDOMAIN_LLDAP"
    volumes:
      - caddy_logs:/var/log/caddy
      - caddy_data:/data
      - caddy_pseudo_config:/config
      - caddy_tor_socket:/run/tor
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

volumes:
  caddy_tor_socket:
    name: ${COMPOSE_PROJECT_NAME}.${MODE}.caddy.tor-socket
  caddy_logs:
    name: ${COMPOSE_PROJECT_NAME}.${MODE}.caddy.logs
  caddy_data:
    name: ${COMPOSE_PROJECT_NAME}.${MODE}.caddy.data
  caddy_pseudo_config:
    name: ${COMPOSE_PROJECT_NAME}.${MODE}.caddy.pseudo_config

configs:
  caddy_caddyfile:
    file: ../Caddyfile
    name: ${COMPOSE_PROJECT_NAME}.caddy.caddyfile
  caddy_entrypoint:
    file: ../entrypoint.sh
    name: ${COMPOSE_PROJECT_NAME}.caddy.entrypoint
