services:
  caddy:
    extends:
      file: ../../compose.yaml.d/compose.yaml
      service: common
    volumes:
      - type: bind
        source: ../site
        target: /srv
        read_only: true
    environment:
      REDIRECTION_AUTHORITY_SUFFIX: "$LOCALHOST_REDIRECTION_SUFFIX"
      CROWDSEC_BOUNCER_KEY: "$development_CROWDSEC_BOUNCER_KEY_CADDY"
      METRICS_PASSWORD_HASH: "$development_METRICS_PASSWORD_HASH_CADDY"
    configs:
      - source: caddy_caddyfile
        target: /etc/caddy/Caddyfile
