services:
  caddy:
    extends:
      file: ../../compose.yaml.d/compose.yaml
      service: common
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - type: bind
        source: ../site
        target: /srv
        read_only: true
    environment:
      REDIRECTION_AUTHORITY_SUFFIX: "$LOCALHOST_REDIRECTION_SUFFIX"
      CROWDSEC_BOUNCER_KEY: "$development_CROWDSEC_BOUNCER_KEY_CADDY"
