include:
  - caddy/compose.yaml.d/compose.yaml

services:
  caddy:
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/site:/srv:ro
    environment:
      LOCALHOST: "${LOCALHOST:-localhost}"
      CROWDSEC_BOUNCER_KEY: "$PRODUCTION_CROWDSEC_BOUNCER_KEY_CADDY"
