services:
  caddy:
    extends:
      file: ../../compose.yaml.d/compose.yaml
      service: common
    environment:
      EMAIL: "$EMAIL"
      CROWDSEC_BOUNCER_KEY: "$production_CROWDSEC_BOUNCER_KEY_CADDY"
    depends_on:
      - crowdsec
      - authelia
