include:
  - compose.yaml

services:
  caddy:
    environment:
      DOMAIN: "$DOMAIN"
      EMAIL: "$EMAIL"
      CROWDSEC_BOUNCER_KEY: "$PRODUCTION_CROWDSEC_BOUNCER_KEY_CADDY"
    depends_on:
      - crowdsec
      - authelia
