include:
  - caddy/compose.yaml.d/compose.yaml

services:
  caddy:
    environment:
      DOMAIN: "$DOMAIN"
      EMAIL: "$EMAIL"
      EXTRA_DIRECTIVES: "import production"
    depends_on:
      - crowdsec
      - authelia
