global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - localhost:9090

  - job_name: caddy
    static_configs:
    - targets:
      - caddy:2019

  - job_name: crowdsec
    static_configs:
    - targets:
      - crowdsec:6060

  - job_name: grafana
    static_configs:
    - targets:
      - grafana:3000

  - job_name: authelia
    static_configs:
    - targets:
      - authelia:9959
