global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alerts.yml

scrape_configs:

  - job_name: authelia
    static_configs:
    - targets:
      - authelia:9959

  - job_name: caddy
    static_configs:
    - targets:
      - caddy:2019
    basic_auth:
      username: prometheus
      password_file: /run/secrets/metrics_password_caddy

  - job_name: crowdsec
    static_configs:
    - targets:
      - crowdsec:6060

  - job_name: grafana
    static_configs:
    - targets:
      - grafana:3000
    basic_auth:
      username: prometheus
      password_file: /run/secrets/metrics_password_grafana

  - job_name: openrc-exporter
    static_configs:
    - targets:
      - openrc-exporter:9816

  - job_name: podman-exporter
    static_configs:
    - targets:
      - podman-exporter:9882

  - job_name: postgres-exporter
    static_configs:
    - targets:
      - postgres-exporter:9187

  - job_name: prometheus
    static_configs:
    - targets:
      - localhost:9090
